name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify release tag matches package version
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          VERSION=$(grep '<Version>' events-sdk-csharp/events-sdk-csharp.csproj | sed "s@.*<Version>\(.*\)</Version>.*@\1@")
          if [ "$TAG" != "$VERSION" ]; then {
            echo "Tag $TAG does not match the package version ($VERSION)"
            exit 1
          } fi

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - run: dotnet pack
        working-directory: events-sdk-csharp

      - name: Publish
        run: dotnet nuget push nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        working-directory: events-sdk-csharp
